### PR TITLE
CORE-275 build Input component

### PR DESCRIPTION
**Pull request by esclapes**
### Purpose
Add and style an `Input` component.

 
### Notes

* The style guide is here: https://buffer.gitbook.io/buffer-design-system/guidelines/forms

#### Staging Deployment

_This repo is CI/CD enabled and staging deployment should be available at:
https://<branch_name>.account.buffer.com :smile:_

### CODE REVIEW

**Comment by hharnisc** [comment]
:ceilingcat: here, we've got an input component in the Buffer Components repo - https://github.com/bufferapp/buffer-components

I thought I might have seen some color and zIndex definitions too, there are some constants that might be helpful:

https://github.com/bufferapp/buffer-components/blob/master/style/zIndex.js
https://github.com/bufferapp/buffer-components/blob/master/style/color.js

**Comment by esclapes** [comment]
@philippemiguet @ssvmvss this is no longer WIP :tada: Looking forward to getting your review and suggestions :raised_hands: 

We still need to add the error icon that shows in the sytleguide, but I am not sure how to approach it yet... Assets per component? shared assets? other? I would love to hear your thoughts on this.

**Comment by ssvmvss** [comment]
@esclapes I really like how everything looks with Styled Components 😄 

What do you think about using rem/em instead of px on units? Like here: https://github.com/bufferapp/buffer-components/blob/master/InputStateless/index.jsx

**Comment by esclapes** [comment]
Hey @ssvmvss, I have just pushed a commit to use some exported `const` to handle typography using 'rem'. How does that look to you?

**Pull request merged**
